#include "admin_routes.h"

#include "http_request.h"
#include "http_response.h"
#include "product_routes.h"
#include "session_store.h"
#include "scc_bcrypt.h"
#include "sqlite3.h"
#include <inja.hpp>
#include <nlohmann/json.hpp>

#include <cstdlib>
#include <iostream>
#include <vector>

namespace {
bool admin(const std::filesystem::path& root, std::string_view request) {
    const auto username = session_username(request); if (username.empty()) return false;
    sqlite3* db=nullptr; const auto file=(root/"data"/"system_control_center.db").string(); if(sqlite3_open_v2(file.c_str(),&db,SQLITE_OPEN_READONLY,nullptr)!=SQLITE_OK)return false;
    sqlite3_stmt* s=nullptr; bool result=false; if(sqlite3_prepare_v2(db,"SELECT role FROM users WHERE username=?1",-1,&s,nullptr)==SQLITE_OK){sqlite3_bind_text(s,1,username.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)==SQLITE_ROW&&sqlite3_column_text(s,0))result=std::string(reinterpret_cast<const char*>(sqlite3_column_text(s,0)))=="admin";}sqlite3_finalize(s);sqlite3_close(db);return result;
}
std::string body_of(std::string_view request){const auto p=request.find("\r\n\r\n");return p==std::string_view::npos?std::string{}:std::string(request.substr(p+4));}
}

std::string entity_list_route(const std::filesystem::path& root, std::string_view request) {
    const auto username=session_username(request); if(username.empty())return redirect("/?error=Please%20sign%20in");
    sqlite3*db=nullptr;const auto file=(root/"data"/"system_control_center.db").string();if(sqlite3_open_v2(file.c_str(),&db,SQLITE_OPEN_READONLY,nullptr)!=SQLITE_OK)return response("500 Internal Server Error","text/plain; charset=utf-8","Database unavailable\n");
    nlohmann::json data;data["username"]=username;data["role"]="viewer";for(const auto& c:{"id","entity_type","name","email","created_at"})data["columns"].push_back(c);sqlite3_stmt*s=nullptr;const char*sql="SELECT e.id, et.entity, e.name, COALESCE(e.email, ''), e.created_at FROM entities e INNER JOIN entity_type et ON e.entity_type = et.id ORDER BY e.name";if(sqlite3_prepare_v2(db,sql,-1,&s,nullptr)==SQLITE_OK)while(sqlite3_step(s)==SQLITE_ROW)data["rows"].push_back({{"id",sqlite3_column_int(s,0)},{"entity_type",reinterpret_cast<const char*>(sqlite3_column_text(s,1))},{"name",reinterpret_cast<const char*>(sqlite3_column_text(s,2))},{"email",reinterpret_cast<const char*>(sqlite3_column_text(s,3))},{"created_at",reinterpret_cast<const char*>(sqlite3_column_text(s,4))}});sqlite3_finalize(s);sqlite3_close(db);
    try{inja::Environment env((root/"templates").string());env.set_html_autoescape(true);return response("200 OK","text/html; charset=utf-8",env.render_file((root/"templates"/"entities.html").string(),data));}catch(const std::exception& error){std::cerr<<"Entities template rendering failed: "<<error.what()<<"\n";return response("500 Internal Server Error","text/plain; charset=utf-8","Entities template unavailable\n");}
}

std::string entity_mutation_route(const std::filesystem::path& root,std::string_view request,std::string_view path){if(session_username(request).empty())return redirect("/?error=Please%20sign%20in");if(!admin(root,request))return redirect("/entities-view?error=Administrator%20access%20required");sqlite3*db=nullptr;const auto file=(root/"data"/"system_control_center.db").string();if(sqlite3_open_v2(file.c_str(),&db,SQLITE_OPEN_READWRITE,nullptr)!=SQLITE_OK)return response("500 Internal Server Error","text/plain; charset=utf-8","Database unavailable\n");const auto body=body_of(request);sqlite3_stmt*s=nullptr;int result=SQLITE_ERROR;if(path=="/entities/create"){result=sqlite3_prepare_v2(db,"INSERT INTO entities (entity_type, name, email) SELECT id, ?2, ?3 FROM entity_type WHERE entity = ?1",-1,&s,nullptr);if(result==SQLITE_OK){const auto type=form_value(body,"entity_type"),name=form_value(body,"name"),email=form_value(body,"email");sqlite3_bind_text(s,1,type.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,name.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,email.c_str(),-1,SQLITE_TRANSIENT);}}else if(path=="/entities/update"){result=sqlite3_prepare_v2(db,"UPDATE entities SET entity_type = (SELECT id FROM entity_type WHERE entity = ?1), name = ?2, email = ?3 WHERE id = ?4",-1,&s,nullptr);if(result==SQLITE_OK){const auto type=form_value(body,"entity_type"),name=form_value(body,"name"),email=form_value(body,"email");sqlite3_bind_text(s,1,type.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,name.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,email.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,4,static_cast<int>(std::strtol(form_value(body,"id").c_str(),nullptr,10)));}}else if(path.rfind("/entities/delete/",0)==0){result=sqlite3_prepare_v2(db,"DELETE FROM entities WHERE id = ?1",-1,&s,nullptr);if(result==SQLITE_OK)sqlite3_bind_int(s,1,static_cast<int>(std::strtol(std::string(path.substr(18)).c_str(),nullptr,10)));}if(result==SQLITE_OK){sqlite3_exec(db,"BEGIN",nullptr,nullptr,nullptr);result=sqlite3_step(s);sqlite3_exec(db,result==SQLITE_DONE?"COMMIT":"ROLLBACK",nullptr,nullptr,nullptr);}sqlite3_finalize(s);sqlite3_close(db);return result==SQLITE_DONE?redirect("/entities-view"):redirect("/entities-view?error=Entity%20operation%20failed");}

std::string user_list_route(const std::filesystem::path& root,std::string_view request){if(session_username(request).empty())return redirect("/?error=Please%20sign%20in");if(!admin(root,request))return redirect("/dashboard?error=Administrator%20access%20required");sqlite3*db=nullptr;const auto file=(root/"data"/"system_control_center.db").string();if(sqlite3_open_v2(file.c_str(),&db,SQLITE_OPEN_READONLY,nullptr)!=SQLITE_OK)return response("500 Internal Server Error","text/plain; charset=utf-8","Database unavailable\n");nlohmann::json data;data["username"]=session_username(request);for(const auto& c:{"id","username","email","role","created_at"})data["columns"].push_back(c);sqlite3_stmt*s=nullptr;if(sqlite3_prepare_v2(db,"SELECT id, username, email, role, created_at FROM users ORDER BY username",-1,&s,nullptr)==SQLITE_OK)while(sqlite3_step(s)==SQLITE_ROW)data["rows"].push_back({{"id",sqlite3_column_int(s,0)},{"username",reinterpret_cast<const char*>(sqlite3_column_text(s,1))},{"email",reinterpret_cast<const char*>(sqlite3_column_text(s,2))},{"role",reinterpret_cast<const char*>(sqlite3_column_text(s,3))},{"created_at",reinterpret_cast<const char*>(sqlite3_column_text(s,4))}});sqlite3_finalize(s);sqlite3_close(db);try{inja::Environment env((root/"templates").string());env.set_html_autoescape(true);return response("200 OK","text/html; charset=utf-8",env.render_file((root/"templates"/"users.html").string(),data));}catch(...){return response("500 Internal Server Error","text/plain; charset=utf-8","Users template unavailable\n");}}

std::string user_mutation_route(const std::filesystem::path& root,std::string_view request,std::string_view path){if(session_username(request).empty())return redirect("/?error=Please%20sign%20in");if(!admin(root,request))return redirect("/dashboard?error=Administrator%20access%20required");sqlite3*db=nullptr;const auto file=(root/"data"/"system_control_center.db").string();if(sqlite3_open_v2(file.c_str(),&db,SQLITE_OPEN_READWRITE,nullptr)!=SQLITE_OK)return response("500 Internal Server Error","text/plain; charset=utf-8","Database unavailable\n");const auto body=body_of(request);const auto username=form_value(body,"username"),email=form_value(body,"email"),role=form_value(body,"role"),password=form_value(body,"password");sqlite3_stmt*s=nullptr;int result=SQLITE_ERROR;if(path=="/users/create"){result=sqlite3_prepare_v2(db,"INSERT INTO users (username, email, password_hash, role) VALUES (?1, ?2, ?3, ?4)",-1,&s,nullptr);if(result==SQLITE_OK){const auto hash=bcrypt::generateHash(password);sqlite3_bind_text(s,1,username.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,email.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,hash.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,role.c_str(),-1,SQLITE_TRANSIENT);}}else if(path=="/users/update"){const bool change=!password.empty();const char*sql=change?"UPDATE users SET username=?1, email=?2, role=?3, password_hash=?4 WHERE id=?5":"UPDATE users SET username=?1, email=?2, role=?3 WHERE id=?4";result=sqlite3_prepare_v2(db,sql,-1,&s,nullptr);if(result==SQLITE_OK){sqlite3_bind_text(s,1,username.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,email.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,role.c_str(),-1,SQLITE_TRANSIENT);if(change){const auto hash=bcrypt::generateHash(password);sqlite3_bind_text(s,4,hash.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,5,static_cast<int>(std::strtol(form_value(body,"id").c_str(),nullptr,10)));}else sqlite3_bind_int(s,4,static_cast<int>(std::strtol(form_value(body,"id").c_str(),nullptr,10)));}}else if(path.rfind("/users/delete/",0)==0){result=sqlite3_prepare_v2(db,"DELETE FROM users WHERE id=?1 AND username != ?2",-1,&s,nullptr);if(result==SQLITE_OK){sqlite3_bind_int(s,1,static_cast<int>(std::strtol(std::string(path.substr(14)).c_str(),nullptr,10)));sqlite3_bind_text(s,2,session_username(request).c_str(),-1,SQLITE_TRANSIENT);}}if(result==SQLITE_OK){sqlite3_exec(db,"BEGIN",nullptr,nullptr,nullptr);result=sqlite3_step(s);sqlite3_exec(db,result==SQLITE_DONE?"COMMIT":"ROLLBACK",nullptr,nullptr,nullptr);}sqlite3_finalize(s);sqlite3_close(db);return result==SQLITE_DONE?redirect("/users-view"):redirect("/users-view?error=User%20operation%20failed");}
